### ISSUE TITLE
No such file or directory (os error 2) when trying to run with default settings

### ISSUE THREAD

**Issue by danieldeankon** [roalyr/pglowrpg#1]
Small issue. The application needs the `./save` directory to already exist when attempting to write to e.g. `./save/island_small_15092020`.

I ran these commands in the terminal:

`$ git clone https://github.com/roalyr/pglowrpg.git`

`$ cd pglowrpg/`

`$ cargo run`

I then hit the enter key twice to select the default preset and seed, getting this terminal output:

```
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
Procedurally Generated Living Open World RPG
@Roal-Yr 2020
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒


Select a preset by entering its name. 
Press Enter to use the preset from worldgen options. 
Available presets (see ./presets/world folder) are listed below:
continent_medium, island_small, 
 >> 
Default seed is from preset, enter 'r' to make it random.
 >> 
Selected preset "island_small"
The amount of worlds to generate is: "1"
Using seed "15092020"
Preparing topography map...
Preparing temperature map...
Preparing watermask map...
Preparing river map...
Accessory maps written
...10%
...20%
...30%
...40%
...50%
...60%
...70%
...80%
...90%
...100%
Preparing biome map...
Preparing georegion map...
No such file or directory (os error 2): ./save/island_small_15092020
```

When I created the `./save` directory, I was able to run the application the same way with no issue. My operating system is Linux Mint 19.2 Cinnamon.

**Comment by roalyr** [comment]
Thank you. I thought I've made directory creation part for the ./save/, but it seems that I've only covered the world-specific folders inside.
