### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by racksonjoss101** [roalyr/pglowrpg#38]
Hello, I have rust and all the things i need to have to run it but I don't know how! Help me please!

-

**Comment by roalyr** [comment]
Hello, download the whole thing, unpack it (or git clone), and execute `cargo run --release` in the folder.

**Comment by roalyr** [comment]
If you've figured it out, feel free to close the issue.

**Comment by racksonjoss101** [comment]
witch folder

**Comment by roalyr** [comment]
In the root folder, obviously. The one that contains README and Cargo.toml.
Open your terminal or powershell, navigate there and in there run `cargo run --release`.
